### ISSUE TITLE
conjunction of two equi-joins is itself an equi-join

### ISSUE THREAD

**Issue by jdegoes** [slamdata/slamengine#847] opened 2015-07-23 14:21 UTC
Query works correctly:

```sql
SELECT c1.name, c2.city
 FROM table1 c1
 JOIN table2 c2 ON c1.userId = c2.userId;
```

Query never returns:

```sql
SELECT c1.name, c2.city
 FROM table1 c1
 JOIN table2 c2 ON c1.userId = c2.userId AND c1.userId = 101;
```

**Comment by sellout** [comment] 2015-07-23 14:27
This is more-or-less a duplicate of #279, although the query should definitely fail, not hang.

**Comment by sellout** [comment] 2015-07-23 14:29
What I’d like to do here, rather than having comparator, lproj, and rproj be part of JoinF is for it to just take an arbitrary LP for the condition.

**Comment by jdegoes** [comment] 2015-07-23 21:01
User verified `JOIN`s work fine with one condition, and not at all with multiple conditions; both `INNER JOIN` and `LEFT OUTER JOIN`.

**Closed** 2015-07-29 17:00 UTC
Labels: enhancement
