### ISSUE TITLE
Allow move files to destination that have "." symbol

### ISSUE THREAD

**Issue by cryogenian** [slamdata/slamengine#818] opened 2015-06-29 23:34 UTC
I'm trying to move something (file, notebook, dir) from `"/path"` to `"/.trash/path"` and got that 
```json
{
    "error": "com.mongodb.MongoCommandException: Command failed with error -1: 'error with target namespace: invalid db name' on server localhost:27017. The full response is { \"ok\" : 0.0, \"errmsg\" : \"error with target namespace: invalid db name\" }"
}
```

moving to `"/trash/path"` works, moving to `"/.smth/path"` doesn't work

**Comment by jdegoes** [comment] 2015-06-30 12:37
Most likely a duplicate of #760.

**Closed** 2015-07-10 17:51 UTC
Labels: bug, in progress
