### ISSUE TITLE
DBObject; cannot be cast to java.util.List in Admin UI

### ISSUE THREAD

**Issue by radbradman** [slamdata/slamengine#616] opened 2015-02-13 02:39 UTC
When attempting to run several simple queries, I get the following exception in the Admin UI:

OS: Windows 7
Version: 1.2.11
Query: select *
  from "/qa3/CalendarItems" where _t = "Appointment"
Stack trace:

Vector(SQL AST
Select
+- Proj
¦  ?- Splice
+- TableRelation(/qa3/CalendarItems)
?- Binop(=)
   +- Ident(_t)
   ?- Ident(Appointment), SQL AST (paths interpreted)
Select
+- Proj
¦  ?- Splice
+- TableRelation(./CalendarItems)
?- Binop(=)
   +- Ident(_t)
   ?- Ident(Appointment), Annotated Tree
Select
+- Annotation
¦  +- None
¦  +- Provenance(Empty)
¦  +- None
¦  ?- Type(NamedField(0,Top))
+- Proj
¦  +- Annotation
¦  ¦  +- None
¦  ¦  +- Provenance(Empty)
¦  ¦  +- None
¦  ¦  ?- Type(Top)
¦  ?- Splice
¦     ?- Annotation
¦        +- None
¦        +- Provenance(Empty)
¦        +- None
¦        ?- Type(Top)
+- TableRelation(./CalendarItems)
¦  ?- Annotation
¦     +- None
¦     +- Provenance(./CalendarItems)
¦     +- None
¦     ?- Type(Bottom)
?- Binop(=)
   +- Annotation
   ¦  +- None
   ¦  +- Provenance(./CalendarItems)
   ¦  +- OneToOne((=))
   ¦  ?- Type(Bool)
   +- Ident(_t)
   ¦  ?- Annotation
   ¦     +- None
   ¦     +- Provenance(./CalendarItems)
   ¦     +- None
   ¦     ?- Type(Top)
   ?- Ident(Appointment)
      ?- Annotation
         +- None
         +- Provenance(./CalendarItems)
         +- None
         ?- Type(Top), Annotated Tree (variables substituted)
Select
+- Annotation
¦  +- None
¦  +- Provenance(Empty)
¦  +- None
¦  ?- Type(NamedField(0,Top))
+- Proj
¦  +- Annotation
¦  ¦  +- None
¦  ¦  +- Provenance(Empty)
¦  ¦  +- None
¦  ¦  ?- Type(Top)
¦  ?- Splice
¦     ?- Annotation
¦        +- None
¦        +- Provenance(Empty)
¦        +- None
¦        ?- Type(Top)
+- TableRelation(./CalendarItems)
¦  ?- Annotation
¦     +- None
¦     +- Provenance(./CalendarItems)
¦     +- None
¦     ?- Type(Bottom)
?- Binop(=)
   +- Annotation
   ¦  +- None
   ¦  +- Provenance(./CalendarItems)
   ¦  +- OneToOne((=))
   ¦  ?- Type(Bool)
   +- Ident(_t)
   ¦  ?- Annotation
   ¦     +- None
   ¦     +- Provenance(./CalendarItems)
   ¦     +- None
   ¦     ?- Type(Top)
   ?- Ident(Appointment)
      ?- Annotation
         +- None
         +- Provenance(./CalendarItems)
         +- None
         ?- Type(Top), Logical Plan
Let('tmp0)
+- Read(./CalendarItems)
?- Let('tmp1)
   +- ManyToMany(WHERE)
   ¦  +- Free('tmp0)
   ¦  ?- OneToOne((=))
   ¦     +- OneToOne(({}))
   ¦     ¦  +- Free('tmp0)
   ¦     ¦  ?- Constant(Data.Str("_t"))
   ¦     ?- OneToOne(({}))
   ¦        +- Free('tmp0)
   ¦        ?- Constant(Data.Str("Appointment"))
   ?- Let('tmp2)
      +- Free('tmp1)
      ?- Let('tmp3)
         +- Squashing(SQUASH)
         ¦  ?- Free('tmp2)
         ?- Free('tmp3), Simplified
Let('tmp0)
+- Read(./CalendarItems)
?- Squashing(SQUASH)
   ?- ManyToMany(WHERE)
      +- Free('tmp0)
      ?- OneToOne((=))
         +- OneToOne(({}))
         ¦  +- Free('tmp0)
         ¦  ?- Constant(Data.Str("_t"))
         ?- OneToOne(({}))
            +- Free('tmp0)
            ?- Constant(Data.Str("Appointment")), Physical Plan
Chain
+- $Read(CalendarItems)
+- $Project
¦  +- Name(__tmp0 -> { "$eq" : [ "$_t" , "$Appointment"]})
¦  +- Name(__tmp1 -> $$ROOT)
¦  ?- IgnoreId
+- $Match
¦  ?- Selector(Doc)
¦     ?- Selector(BsonField.Name("__tmp0") -> Eq(Bool(true)))
?- $Project
   +- Name(value -> $__tmp1)
   ?- ExcludeId, Mongo
db.CalendarItems.aggregate([
    { "$project" : { "__tmp0" : { "$eq" : [ "$_t" , "$Appointment"]} , "__tmp1" : "$$ROOT"}},
    { "$match" : { "__tmp0" : true}},
    { "$project" : { "value" : "$__tmp1" , "_id" : false}},
    { "$out" : "tmp.gen_0"}
  ],
  { allowDiskUse: true })
db.tmp.gen_0.find())

An error occurred during evaluation: java.lang.ClassCastException: [Lcom.mongodb.DBObject; cannot be cast to java.util.List
slamdata.engine.physical.mongodb.MongoDbExecutor$$anonfun$runMongoCommand$1$$anonfun$apply$29.apply(evaluator.scala:287)
slamdata.engine.physical.mongodb.MongoDbExecutor$$anonfun$runMongoCommand$1$$anonfun$apply$29.apply(evaluator.scala:287)
  ... (1)
slamdata.engine.physical.mongodb.MongoDbExecutor$$anonfun$runMongoCommand$1.apply(evaluator.scala:286)
slamdata.engine.physical.mongodb.MongoDbExecutor$$anonfun$runMongoCommand$1.apply(evaluator.scala:284)
  ... (34)

**Comment by mossprescott** [comment] 2015-02-13 16:36
I'm not sure what's going on there. Can you tell us what version of MongoDB you're using, and include the rest of the stack trace?

Also, there's a minor problem with the query, which is that the string `Appointment` should be enclosed in single quotes, as in `select *
from "/qa3/CalendarItems" where _t = 'Appointment'`. With double quotes, it's actually referring to a field named Appointment, which probably isn't what you want.

**Comment by jdegoes** [comment] 2015-02-13 17:17
@mossprescott The error is the `ClastCastException`, which should never happen in our code base:

```
java.lang.ClassCastException: [Lcom.mongodb.DBObject; cannot be cast to java.util.List
slamdata.engine.physical.mongodb.MongoDbExecutor$$anonfun$runMongoCommand$1$$anonfun$apply$29.apply(evaluator.scala:287)
```

The code needs to be rewritten to become type safe.

**Comment by mossprescott** [comment] 2015-02-13 17:26
Agreed. The reason I asked for the full stack trace is the error seems to be occurring in the MongoDB driver and is just getting wrapped at that location. We're certainly not doing a cast there, anyway.

Also I tried several variations of this query and did not see any errors like that, so I'm not sure what the ultimate cause might be.

**Comment by jdegoes** [comment] 2015-02-13 17:34
Yes, the error seems to be thrown from the client library.

The error would most likely be that we are generating a `DBObject` in a place where Mongo's client library expects a `java.util.List`.

**Comment by mossprescott** [comment] 2015-02-13 17:39
That's certainly a possibility. Any ideas about how to reproduce it so I can investigate?

**Comment by jdegoes** [comment] 2015-02-13 17:48
No great ones. :)

1. Use the latest SlamData from the website, since I know @radbradman used that version (just in case it's fixed in head, unlikely but possible).
2. The dump includes the query plan:
   ```javascript
   db.CalendarItems.aggregate([
     { "$project" : { "__tmp0" : { "$eq" : [ "$_t" , "$Appointment"]} , "__tmp1" : "$$ROOT"}},
     { "$match" : { "__tmp0" : true}},
     { "$project" : { "value" : "$__tmp1" , "_id" : false}},
     { "$out" : "tmp.gen_0"}
   ],
   { allowDiskUse: true })
   ```
   We know that `$Appointment` does not exist in the data set. We would also expect that `_t` is a String field because that's the way it's being used in the query.
3. If the above query plan and constraints cannot reproduce it, it's possible the actual data structures being used by the MongoDB evaluator differ from the Javascript query plan.

**Comment by mossprescott** [comment] 2015-02-13 18:11
I've tried every similar query I can think of, both in master and in 1.2.11, and I'm not seeing any errors of any kind.

@radbradman, anything more you can tell us about your setup might be helpful.
- MongoDB version
- Other queries that do work?
- Sample of the data in `qa2.CalendarItems`, and the expected output?

**Comment by radbradman** [comment] 2015-02-13 19:42
Certainly.  
MongoDB version is 2.6.5

Queries that do work: select * from "/qa3/CalendarItems"

As soon as a I add a where clause (doesn't seem to matter what is in it) it fails (for example:
 select * from "/qa3/CalendarItems" where ClientId = 13507 also fails)

Here is a sample record of what a CalendarItem looks like; the expected output would be all columns where _t is equal to "Appointment", which should output a few hundred rows in my sample set.

{
    "_id" : ObjectId("54db9647b1d6fd188c1c3983"),
    "_t" : "Appointment",
    "IsDeleted" : false,
    "CreatedBy" : 0,
    "UpdatedBy" : 0,
    "UpdatedAt" : ISODate("2015-02-11T17:49:59.478Z"),
    "CreatedAt" : ISODate("2015-02-11T17:49:59.478Z"),
    "ClientId" : 13507,
    "ServiceProviderId" : ObjectId("53f3c27a04ce7236d8e94742"),
    "StartAt" : ISODate("2015-01-21T17:05:00.000Z"),
    "EndAt" : ISODate("2015-01-21T17:20:00.000Z"),
    "Customer" : {
        "_id" : null,
        "FirstName" : "John",
        "LastName" : "Kimble",
        "Email" : "johnKimble@paysimple.com",
        "Phone" : "3949495968"
    },
    "Offering" : {
        "_id" : ObjectId("5437285304ce7a59d40ebe95"),
        "Name" : "Beard Trim",
        "BufferMinutes" : 5
    }
}

**Comment by mossprescott** [comment] 2015-02-13 20:01
Thanks, @radbradman.

Unfortunately, I'm stumped. I added that single object to our MongoDB instance, also running 2.6.5, and ran several versions of the query with and without filtering. The original query, with the quoting problem, gives me no results and no error. The same query but with single quotes around `'Appointment'`, gives me back the one result.

About the only thing I can think of is that if we could capture some more information about where the error occurred we might be able to track it down in the MongoDB driver. I believe this will require a small code change, so I'll let you know.

**Comment by sellout** [comment] 2015-02-13 20:25
I know we’re on the JVM, but maybe this is somehow platform-specific? Perhaps @JeffACarr could try it out?

**Comment by radbradman** [comment] 2015-02-13 20:43
I've noticed a few more things....this is very strange.

On our mongolab instance, it does not matter which collection I am
selecting from, I still get this exception whenever the plan uses the
aggregation framework.  When it is a simple find() it works fine.  However,
when I take the query out from the "plan" pane and execute them in MongoDb
directly (outside of slamdata) using the same username/pw, it executes
without error.

When I connect to a local instance (2.6.3), aggregation queries on the same
collections I am querying on the mongolab instance work fine.

Is there anything I have to do to a default mongolab instance or new user
to get it to work with slamdata aggregation framework queries?

**Comment by mossprescott** [comment] 2015-02-13 21:53
@radbradman: your comments got me thinking in a new direction and I believe I may have hit on the problem. I can't explain why it works in every setup we've tried except yours, but I made a change to construct the command in a way which should fix the problem, if my guess is right.

You can download that build here: https://github.com/slamdata/slamengine/releases/tag/v1.2.12-SNAPSHOT-924-admin

Please give it a try and let us know.

**Comment by radbradman** [comment] 2015-02-13 22:42
Yup, that fixed it!  Thanks a bunch!!

**Comment by mossprescott** [comment] 2015-02-13 22:47
Awesome. Thanks for your patience and persistence!

**Closed by mossprescott** 2015-02-13 22:47 UTC
Labels: bug, ready
