### ISSUE TITLE
evaluator: improve performance of JOINs through jsMode

### ISSUE THREAD

**Issue by pjaffe** [slamdata/slamengine#586] opened 2015-01-31 22:44 UTC
I just recently reported #585 that described some behavior of JOIN that didn't seem correct to me.  However, if I turn a blind eye to that, I tried to run a JOIN on some decent sized collections, but ones that were a small fraction of our expected size.  After about 15-20 seconds of execution time, I end up with the following result:

1. My Mongo 2.6.7 process gets terminated (it is running on a 64-bit Windows 7 machine from a command prompt)
2. Within the 400 or so lines appended to the mongo server log during the SlamSQL processing period, I see the following toward the end:
```
2015-01-31T17:27:59.369-0500 [conn6] Assertion: 13548:BufBuilder attempted to grow() to 134217728 bytes, past the 64MB limit.
```
and a few lines after that is the following, which looks to me like a mongo stack trace and also includes a reference to the BufBuilder
```
2015-01-31T17:28:00.054-0500 [conn6] mongod.exe  ...\src\mongo\util\stacktrace.cpp(169)       mongo::printStackTrace+0x43
2015-01-31T17:28:00.054-0500 [conn6] mongod.exe  ...\src\mongo\util\log.cpp(127)              mongo::logContext+0x9c
2015-01-31T17:28:00.054-0500 [conn6] mongod.exe  ...\src\mongo\util\assert_util.cpp(183)      mongo::msgasserted+0xfb
2015-01-31T17:28:00.054-0500 [conn6] mongod.exe  ...\src\mongo\bson\util\builder.h(220)       mongo::_BufBuilder<mongo::TrivialAllocator>::grow_reallocate+0x175
2015-01-31T17:28:00.055-0500 [conn6] mongod.exe  ...\src\mongo\bson\bsonobjbuilder.h(387)     mongo::BSONObjBuilder::append+0x119
2015-01-31T17:28:00.055-0500 [conn6] mongod.exe  ...\src\mongo\db\pipeline\value.cpp(279)     mongo::operator<<+0x17c
```

I found the following comment on a Mongo issue https://jira.mongodb.org/browse/SERVER-5125?focusedCommentId=714361&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-714361 which implies to me (based on a quick read) that maybe this needs to be addressed in the SlamEngine via some refinement of the use of the $out operator.  But I absolutely didn't try to dig into this in any depth.

If I take the Compiled plan that SlamData generates, and run it in Robomongo, it executes for 20+ seconds (roughly the same amount of time, but it seems a little longer), and I see some results, but also the following output: 
```
Error("Printing Stack Trace")@:0
()@src/mongo/shell/utils.js:37
([object Array],[object Object])@src/mongo/shell/collection.js:866
@(shell):6

uncaught exception: aggregate failed: {
	"errmsg" : "exception: Exceeded memory limit for $group, but didn't allow external sort. Pass allowDiskUse:true to opt in.",
	"code" : 16945,
	"ok" : 0
}
```

The query I'm trying to run is 
```sql
SELECT COUNT(*) 
FROM "/UserAccount" p 
LEFT OUTER JOIN "/Credential" c ON c.userId = p._id
```
The two collections have 300K and 227K documents respectively.

Here is what I see in the SlamData logging pane:
```javascript
Vector(SQL AST
Select
├─ Proj
│  ╰─ InvokeFunction(COUNT)
│     ╰─ Splice
╰─ JoinRelation((LeftJoin))
   ├─ TableRelation(/UserAccount as p)
   ├─ TableRelation(/Credential as c)
   ╰─ Binop(=)
      ├─ Binop({})
      │  ├─ Ident(c)
      │  ╰─ LiteralExpr('userId')
      ╰─ Binop({})
         ├─ Ident(p)
         ╰─ LiteralExpr('_id'), SQL AST (paths interpreted)
Select
├─ Proj
│  ╰─ InvokeFunction(COUNT)
│     ╰─ Splice
╰─ JoinRelation((LeftJoin))
   ├─ TableRelation(./UserAccount as p)
   ├─ TableRelation(./Credential as c)
   ╰─ Binop(=)
      ├─ Binop({})
      │  ├─ Ident(c)
      │  ╰─ LiteralExpr('userId')
      ╰─ Binop({})
         ├─ Ident(p)
         ╰─ LiteralExpr('_id'), Annotated Tree
Select
├─ Annotation
│  ├─ None
│  ├─ Provenance(Empty)
│  ├─ None
│  ╰─ Type(NamedField(0,Int))
├─ Proj
│  ├─ Annotation
│  │  ├─ None
│  │  ├─ Provenance(Empty)
│  │  ├─ None
│  │  ╰─ Type(Int)
│  ╰─ InvokeFunction(COUNT)
│     ├─ Annotation
│     │  ├─ None
│     │  ├─ Provenance(Empty)
│     │  ├─ ManyToOne(COUNT)
│     │  ╰─ Type(Int)
│     ╰─ Splice
│        ╰─ Annotation
│           ├─ None
│           ├─ Provenance(Empty)
│           ├─ None
│           ╰─ Type(Top)
╰─ JoinRelation((LeftJoin))
   ├─ Annotation
   │  ├─ None
   │  ├─ Provenance((LeftJoin))
   │  │  ├─ TableRelation(./UserAccount as p)
   │  │  ├─ TableRelation(./Credential as c)
   │  │  ╰─ Binop(=)
   │  │     ├─ Binop({})
   │  │     │  ├─ Ident(c)
   │  │     │  ╰─ LiteralExpr('userId')
   │  │     ╰─ Binop({})
   │  │        ├─ Ident(p)
   │  │        ╰─ LiteralExpr('_id')
   │  ├─ None
   │  ╰─ Type(Bool)
   ├─ TableRelation(./UserAccount as p)
   │  ╰─ Annotation
   │     ├─ None
   │     ├─ Provenance(./UserAccount as p)
   │     ├─ None
   │     ╰─ Type(Bottom)
   ├─ TableRelation(./Credential as c)
   │  ╰─ Annotation
   │     ├─ None
   │     ├─ Provenance(./Credential as c)
   │     ├─ None
   │     ╰─ Type(Bottom)
   ╰─ Binop(=)
      ├─ Annotation
      │  ├─ None
      │  ├─ Provenance(((./Credential as c & Value) & ./UserAccount as p))
      │  ├─ OneToOne((=))
      │  ╰─ Type(Bool)
      ├─ Binop({})
      │  ├─ Annotation
      │  │  ├─ None
      │  │  ├─ Provenance((./Credential as c & Value))
      │  │  ├─ OneToOne(({}))
      │  │  ╰─ Type(Top)
      │  ├─ Ident(c)
      │  │  ╰─ Annotation
      │  │     ├─ None
      │  │     ├─ Provenance(./Credential as c)
      │  │     ├─ None
      │  │     ╰─ Type(AnonField(Top))
      │  ╰─ LiteralExpr('userId')
      │     ╰─ Annotation
      │        ├─ None
      │        ├─ Provenance(Value)
      │        ├─ None
      │        ╰─ Type(Const(Data.Str("userId")))
      ╰─ Binop({})
         ├─ Annotation
         │  ├─ None
         │  ├─ Provenance((./UserAccount as p & Value))
         │  ├─ OneToOne(({}))
         │  ╰─ Type(Top)
         ├─ Ident(p)
         │  ╰─ Annotation
         │     ├─ None
         │     ├─ Provenance(./UserAccount as p)
         │     ├─ None
         │     ╰─ Type(AnonField(Top))
         ╰─ LiteralExpr('_id')
            ╰─ Annotation
               ├─ None
               ├─ Provenance(Value)
               ├─ None
               ╰─ Type(Const(Data.Str("_id"))), Annotated Tree (variables substituted)
Select
├─ Annotation
│  ├─ None
│  ├─ Provenance(Empty)
│  ├─ None
│  ╰─ Type(NamedField(0,Int))
├─ Proj
│  ├─ Annotation
│  │  ├─ None
│  │  ├─ Provenance(Empty)
│  │  ├─ None
│  │  ╰─ Type(Int)
│  ╰─ InvokeFunction(COUNT)
│     ├─ Annotation
│     │  ├─ None
│     │  ├─ Provenance(Empty)
│     │  ├─ ManyToOne(COUNT)
│     │  ╰─ Type(Int)
│     ╰─ Splice
│        ╰─ Annotation
│           ├─ None
│           ├─ Provenance(Empty)
│           ├─ None
│           ╰─ Type(Top)
╰─ JoinRelation((LeftJoin))
   ├─ Annotation
   │  ├─ None
   │  ├─ Provenance((LeftJoin))
   │  │  ├─ TableRelation(./UserAccount as p)
   │  │  ├─ TableRelation(./Credential as c)
   │  │  ╰─ Binop(=)
   │  │     ├─ Binop({})
   │  │     │  ├─ Ident(c)
   │  │     │  ╰─ LiteralExpr('userId')
   │  │     ╰─ Binop({})
   │  │        ├─ Ident(p)
   │  │        ╰─ LiteralExpr('_id')
   │  ├─ None
   │  ╰─ Type(Bool)
   ├─ TableRelation(./UserAccount as p)
   │  ╰─ Annotation
   │     ├─ None
   │     ├─ Provenance(./UserAccount as p)
   │     ├─ None
   │     ╰─ Type(Bottom)
   ├─ TableRelation(./Credential as c)
   │  ╰─ Annotation
   │     ├─ None
   │     ├─ Provenance(./Credential as c)
   │     ├─ None
   │     ╰─ Type(Bottom)
   ╰─ Binop(=)
      ├─ Annotation
      │  ├─ None
      │  ├─ Provenance(((./Credential as c & Value) & ./UserAccount as p))
      │  ├─ OneToOne((=))
      │  ╰─ Type(Bool)
      ├─ Binop({})
      │  ├─ Annotation
      │  │  ├─ None
      │  │  ├─ Provenance((./Credential as c & Value))
      │  │  ├─ OneToOne(({}))
      │  │  ╰─ Type(Top)
      │  ├─ Ident(c)
      │  │  ╰─ Annotation
      │  │     ├─ None
      │  │     ├─ Provenance(./Credential as c)
      │  │     ├─ None
      │  │     ╰─ Type(AnonField(Top))
      │  ╰─ LiteralExpr('userId')
      │     ╰─ Annotation
      │        ├─ None
      │        ├─ Provenance(Value)
      │        ├─ None
      │        ╰─ Type(Const(Data.Str("userId")))
      ╰─ Binop({})
         ├─ Annotation
         │  ├─ None
         │  ├─ Provenance((./UserAccount as p & Value))
         │  ├─ OneToOne(({}))
         │  ╰─ Type(Top)
         ├─ Ident(p)
         │  ╰─ Annotation
         │     ├─ None
         │     ├─ Provenance(./UserAccount as p)
         │     ├─ None
         │     ╰─ Type(AnonField(Top))
         ╰─ LiteralExpr('_id')
            ╰─ Annotation
               ├─ None
               ├─ Provenance(Value)
               ├─ None
               ╰─ Type(Const(Data.Str("_id"))), Logical Plan
Let('tmp0)
├─ Let('left1)
│  ├─ Read(./UserAccount)
│  ╰─ Let('right2)
│     ├─ Read(./Credential)
│     ╰─ Join(LeftOuter, (=))
│        ├─ Free('left1)
│        ├─ Free('right2)
│        ├─ OneToOne(({}))
│        │  ├─ Free('right2)
│        │  ╰─ Constant(Data.Str("userId"))
│        ╰─ OneToOne(({}))
│           ├─ Free('left1)
│           ╰─ Constant(Data.Str("_id"))
╰─ Let('tmp3)
   ├─ OneToOne(MAKE_OBJECT)
   │  ├─ Constant(Data.Str("0"))
   │  ╰─ ManyToOne(COUNT)
   │     ╰─ OneToOne(OBJECT_CONCAT)
   │        ├─ OneToOne(({}))
   │        │  ├─ Free('tmp0)
   │        │  ╰─ Constant(Data.Str("left"))
   │        ╰─ OneToOne(({}))
   │           ├─ Free('tmp0)
   │           ╰─ Constant(Data.Str("right"))
   ╰─ Let('tmp4)
      ├─ Squashing(SQUASH)
      │  ╰─ Free('tmp3)
      ╰─ Free('tmp4), Simplified
Let('tmp0)
├─ Let('left1)
│  ├─ Read(./UserAccount)
│  ╰─ Let('right2)
│     ├─ Read(./Credential)
│     ╰─ Join(LeftOuter, (=))
│        ├─ Free('left1)
│        ├─ Free('right2)
│        ├─ OneToOne(({}))
│        │  ├─ Free('right2)
│        │  ╰─ Constant(Data.Str("userId"))
│        ╰─ OneToOne(({}))
│           ├─ Free('left1)
│           ╰─ Constant(Data.Str("_id"))
╰─ Squashing(SQUASH)
   ╰─ OneToOne(MAKE_OBJECT)
      ├─ Constant(Data.Str("0"))
      ╰─ ManyToOne(COUNT)
         ╰─ OneToOne(OBJECT_CONCAT)
            ├─ OneToOne(({}))
            │  ├─ Free('tmp0)
            │  ╰─ Constant(Data.Str("left"))
            ╰─ OneToOne(({}))
               ├─ Free('tmp0)
               ╰─ Constant(Data.Str("right")), Physical Plan
Chain
├─ $FoldLeft
│  ├─ Chain
│  │  ├─ $Read(UserAccount)
│  │  ├─ $Group
│  │  │  ├─ Grouped
│  │  │  │  ╰─ Name(left -> { "$push" : "$$ROOT"})
│  │  │  ╰─ By(DocField(BsonField.Name("userId")))
│  │  ╰─ $Project
│  │     ├─ Name(left -> $left)
│  │     ├─ Name(right -> { "$literal" : [ ]})
│  │     ╰─ IncludeId
│  ╰─ Chain
│     ├─ $Read(Credential)
│     ├─ $Map
│     │  ╰─ JavaScript(function (key, value) {
│     │                  return [(value != null) ? value._id : undefined, {
│     │                    "left": [],
│     │                    "right": [value]
│     │                  }];
│     │                })
│     ╰─ $Reduce
│        ╰─ JavaScript(function (key, values) {
│                        var result = {
│                          "left": [],
│                          "right": []
│                        };
│                        values.forEach(function (value) {
│                            result.left = result.left.concat(value.left);
│                            result.right = result.right.concat(value.right);
│                          });
│                        return result;
│                      })
├─ $Match
│  ╰─ Selector(Doc)
│     ╰─ Selector(BsonField.Name("left") -> NotExpr(Size(0)))
├─ $Project
│  ├─ Name(left -> $left)
│  ├─ Name(right -> { "$cond" : [ { "$eq" : [ { "$size" : "$right"} , { "$literal" : 0}]} , { "$literal" : [ { }]} , "$right"]})
│  ╰─ IgnoreId
├─ $Unwind(DocField(BsonField.Name("left")))
├─ $Unwind(DocField(BsonField.Name("right")))
├─ $Map
│  ╰─ JavaScript(function (key, __arg0) {
│                  return [key, (function (rez) {
│                      for (var attr in ((__arg0 != null) ? __arg0.left : undefined)) if (((__arg0.left != null) && (__arg0.left.hasOwnProperty != null)) ? __arg0.left.hasOwnProperty(attr) : undefined) (rez != null) ? rez[attr] = ((__arg0 != null) && (__arg0.left != null)) ? __arg0.left[attr] : undefined : undefined;
│                      for (var attr in ((__arg0 != null) ? __arg0.right : undefined)) if (((__arg0.right != null) && (__arg0.right.hasOwnProperty != null)) ? __arg0.right.hasOwnProperty(attr) : undefined) (rez != null) ? rez[attr] = ((__arg0 != null) && (__arg0.right != null)) ? __arg0.right[attr] : undefined : undefined;
│                      return rez;
│                    })({})];
│                })
╰─ $Group
   ├─ Grouped
   │  ╰─ Name(0 -> { "$sum" : { "$literal" : 1}})
   ╰─ By(Literal(Null)), Mongo
db.UserAccount.aggregate([
    { "$group" : { "left" : { "$push" : "$$ROOT"} , "_id" : "$userId"}},
    { "$project" : { "value" : { "left" : "$left" , "right" : { "$literal" : [ ]}}}},
    { "$out" : "tmp.gen_0"}
  ],
  { allowDiskUse: true })
db.Credential.mapReduce(
  function () {
    emit.apply(null, (function (key, value) {
        return [(value != null) ? value._id : undefined, {
          "left": [],
          "right": [value]
        }];
      })(this._id, this));
  },
  function (key, values) {
    var result = {
      "left": [],
      "right": []
    };
    values.forEach(function (value) {
        result.left = result.left.concat(value.left);
        result.right = result.right.concat(value.right);
      });
    return result;
  },
  { "out" : { "reduce" : "tmp.gen_0" , "nonAtomic" : true}})
db.tmp.gen_0.aggregate([
    { "$match" : { "value.left" : { "$not" : { "$size" : 0}}}},
    { "$project" : { "left" : "$value.left" , "right" : { "$cond" : [ { "$eq" : [ { "$size" : "$value.right"} , { "$literal" : 0}]} , { "$literal" : [ { }]} , "$value.right"]}}},
    { "$out" : "tmp.gen_1"}
  ],
  { allowDiskUse: true })
db.tmp.gen_1.mapReduce(
  function () {
    (function (key, value) {
        return [].concat.apply([], (function (key, value) {
            var rez = [];
            for (var elem in ((value != null) ? value.left : undefined)) {
              var each = {};
              for (var attr in (value)) if (((value != null) && (value.hasOwnProperty != null)) ? value.hasOwnProperty(attr) : undefined) (each != null) ? each[attr] = (value != null) ? value[attr] : undefined : undefined;
              (each != null) ? each.left = ((value != null) && (value.left != null)) ? value.left[elem] : undefined : undefined;
              ((rez != null) && (rez.push != null)) ? rez.push([ObjectId(), each]) : undefined;
            };
            return rez;
          })(key, value).map(function (args) {
            return (function (key, value) {
                return (function (key, value) {
                    var rez = [];
                    for (var elem in ((value != null) ? value.right : undefined)) {
                      var each = {};
                      for (var attr in (value)) if (((value != null) && (value.hasOwnProperty != null)) ? value.hasOwnProperty(attr) : undefined) (each != null) ? each[attr] = (value != null) ? value[attr] : undefined : undefined;
                      (each != null) ? each.right = ((value != null) && (value.right != null)) ? value.right[elem] : undefined : undefined;
                      ((rez != null) && (rez.push != null)) ? rez.push([ObjectId(), each]) : undefined;
                    };
                    return rez;
                  })(key, value).map(function (args) {
                    return (function (key, __arg0) {
                        return [key, (function (rez) {
                            for (var attr in ((__arg0 != null) ? __arg0.left : undefined)) if (((__arg0.left != null) && (__arg0.left.hasOwnProperty != null)) ? __arg0.left.hasOwnProperty(attr) : undefined) (rez != null) ? rez[attr] = ((__arg0 != null) && (__arg0.left != null)) ? __arg0.left[attr] : undefined : undefined;
                            for (var attr in ((__arg0 != null) ? __arg0.right : undefined)) if (((__arg0.right != null) && (__arg0.right.hasOwnProperty != null)) ? __arg0.right.hasOwnProperty(attr) : undefined) (rez != null) ? rez[attr] = ((__arg0 != null) && (__arg0.right != null)) ? __arg0.right[attr] : undefined : undefined;
                            return rez;
                          })({})];
                      }).apply(null, args);
                  });
              }).apply(null, args);
          }));
      })(this._id, this).map(function (__rez) {
        emit.apply(null, __rez);
      });
  },
  function (key, values) {
    return (values != null) ? values[0] : undefined;
  },
  { "out" : { "replace" : "tmp.gen_2"}})
db.tmp.gen_2.aggregate([
    { "$group" : { "0" : { "$sum" : { "$literal" : 1}} , "_id" : { "$literal" :  null }}},
    { "$out" : "tmp.gen_3"}
  ],
  { allowDiskUse: true })
db.tmp.gen_0.drop()
db.tmp.gen_1.drop()
db.tmp.gen_2.drop()
db.tmp.gen_3.find())

An error occurred during evaluation: com.mongodb.MongoException$Network: Read operation to server localhost:27017 failed on database SlamDataExample
slamdata.engine.physical.mongodb.MongoDbExecutor$$anonfun$runMongoCommand$1$$anonfun$apply$29.apply(evaluator.scala:287)
slamdata.engine.physical.mongodb.MongoDbExecutor$$anonfun$runMongoCommand$1$$anonfun$apply$29.apply(evaluator.scala:287)
  ... (1)
slamdata.engine.physical.mongodb.MongoDbExecutor$$anonfun$runMongoCommand$1.apply(evaluator.scala:286)
slamdata.engine.physical.mongodb.MongoDbExecutor$$anonfun$runMongoCommand$1.apply(evaluator.scala:284)
  ... (34)
```

**Comment by mossprescott** [comment] 2015-02-01 01:23
We'll have to take a closer look at this. Joins are not well-optimized yet, and that's a larger issue, but hopefully the problem of trying to collate in memory is something we can easily fix.

You may have better luck by simplifying the query somewhat, but my experiments showed only modest improvements. For example, you could try these:
```sql
SELECT COUNT(*) 
FROM "/UserAccount" p 
JOIN "/Credential" c ON c.userId = p._id
```

```sql
SELECT p._id as id, p.name 
FROM "/UserAccount" p 
JOIN "/Credential" c ON c.userId = p._id
```

**Comment by jdegoes** [comment] 2015-02-01 23:26
It looks like two things are happening here:

1. The compiled query plan is not actually the same as the one we execute, mainly because the compiled plan does not allow $group to spill out onto disk, whereas our evaluator does allow this (@mossprescott, please correct me if I'm wrong!). As a result, Robomongo actually fails earlier at a different point, with a different error than our own evaluator, and this error is probably not all that relevant. We should, however, make sure that the compiled query plan actually has the same options as the evaluated query plan (including allowing spilling to disk for large $group operations).
2. The fact that Mongo is dying is not good. We'll investigate this. As far as I know, we already use $out for every query through the aggregation framework, but it's possible some other circumstance triggers this error. In any case, we'll find out what's going wrong and also work with MongoDB (if necessary) to help resolve this issue.

We may have to generate some sample data to reproduce this properly.

@pjaffe, do you know if there is any degenerate data? For example, a degenerate user id and credential id key which could produce a large cross product in the join?

**Comment by sellout** [comment] 2015-02-02 04:05
Well, the compiled plan does include `allowDiskUse: true`, so assuming @pjaffe copied the whole thing, I don’t know why Robomongo wouldn’t have seen that. Since the Robomongo error mentions `$group`, it must be either in the first or final `aggregate()` and, while I’d like to replace the final one with a call to `collection.count()`, it seems much more likely that the first would run out of memory (but again, it should be using `allowDiskUse` already).

The error in _actual_ Mongo is a (now obvious) bug in joins … if you look at the compiled plan, you can see that the initial aggregation is operating on the `UserAccount` collection, but the `$group` is grouping by `$userId`, which is a field in the `Credential` collection, and vice versa for the mapReduce on `Credential`. So, `UserAccount.userId` evaluates to `undefined` on each document, and so we end up collecting the entire collection into one document, which is then too big to deal with.

So, this bug seems small but very significant. I’ll take a look in the morning. In the meantime, try your original query with just the condition reversed:
```sql
SELECT COUNT(*) 
FROM "/UserAccount" p 
LEFT OUTER JOIN "/Credential" c ON p._id = c.userId
```

**Comment by pjaffe** [comment] 2015-02-02 13:43
I confirmed that reversing the equality of the JOIN condition did fix the result, and I'm glad it likely shares a common root problem with #585 . Thanks for that tip.

My JOIN query did take a long time to run (several minutes).  Is that something you think I should report as a separate issue, or is that just the nature of joining across collections?

**Comment by jdegoes** [comment] 2015-02-02 15:23
JOINs are expected to take a while to complete, because they have to fallback to MapReduce machinery. That said, if you think a JOIN is taking an unreasonably long time, then we're happy to take a look at the MongoDB query plan and make sure it's efficiently constructed.

One thing that may be useful is to pre-JOIN the data into a temporary collection. Then you can write queries to run on-the-fly on the pre-JOINed data set, since generally, they will be able to take advantage of indexes on the collection (assuming we don't have to fallback to MapReduce).

**Comment by sellout** [comment] 2015-02-05 18:12
So, the original issue here is the same as #585, which is fixed. The remaining issue seems to be “joins can be slow” – which is a fine issue, but is the resolution for this then 1-bucket θJoins, or what?

Just not sure what the next step should be, and I’m guessing θJoins aren’t a 1.3 feature, because they require some other supporting changes.

**Comment by jdegoes** [comment] 2015-02-07 16:06
A quicker fix (and one that could lead to a several fold speedup) would be `jsMode`, which just requires revising maybe `WorkflowTask` to support an ordered `Choice` task. Then we can try `jsMode`, and it it fails due to too many keys, revert to non-jsMode. That dumb approach can be augmented with cardinality estimates to recommend trying `jsMode` only if there's a good chance it will succeed.

**Comment by sellout** [comment] 2015-02-07 16:56
Ok, there’s some more details about how to do `jsMode` in #341, and I think we could do this without a `Choice` task.

* [ ] Have `MapReduceTask` try once with `jsMode` then again without if it fails (ideally, check the error code),
* [ ] add a `count()` call to determine if we should even attempt the `jsMode` approach, and
* [ ] add `maxEmits` to `MapReduceTask` to get a better idea of when `jsMode` will work.

**Comment by mossprescott** [comment] 2015-02-13 17:19
I just tried turning on jsMode in a simple map-reduce-using query and a simple join, and noticed a couple of things:
- the setter to turn it on in `MapReduceCommand` is added in driver version 2.13.0, although it could probably be done using the "raw" command approach in earlier versions.
- I see no change in performance between jsMode and non-jsMode. My simple query took about 7s, and the join took between 25s and 40s, seemingly at random, with or without jsMode.

It's probably worth more investigation, but this suggests to me that the performance gains are likely to be only in particular circumstances that I didn't encounter in a simple tests.

**Comment by jdegoes** [comment] 2015-02-13 17:21
The data volume is too small to notice. The overhead of invoking V8, etc., is likely to overcome any performance difference. Can you try joins on a, e.g. 50GB data set?

**Comment by jdegoes** [comment] 2015-02-13 17:22
That is, when M/R are taking "tens of minutes", that's when I would expect both (a) consistent timing results (assuming no load on Mongo), and (b) a win for conversion.

I should also say that our relatively unoptimized JS could potentially dominate the runtime... TBD.

**Comment by mossprescott** [comment] 2015-02-13 17:37
No, I don't have any 50GB datasets, or a place to load one, as far as I know. And running comparisons of several-minute joins would exceed the time I was planning to put into this at this moment ;)

I just tried it because @sellout and I were wondering about it yesterday and I figured I'd record my experiences for future reference.

**Comment by jdegoes** [comment] 2015-02-13 17:38
OK, before anyone works on this, though, let's do a 50GB test or so and make sure the performance difference warrants the extra complexity.

**Comment by mossprescott** [comment] 2015-02-13 17:43
Sounds good.

And I'll just mention #341, calling for intelligent use of jsMode, so .

**Comment by mossprescott** [comment] 2015-02-13 17:44
Arg, having trouble with buttons today. Please ignore the thrashing.

**Comment by jdegoes** [comment] 2015-03-03 18:17
Closing as a duplicate of #341.

**Closed** 2015-03-03 23:29 UTC
Labels: enhancement
