### ISSUE TITLE
Mounting a database causes a redirect to localhost:xxxxx

### ISSUE THREAD

**Issue by jonsterling** [slamdata/slamengine#866] opened 2015-08-12 19:18 UTC
It is not entirely clear to me whether this is a bug in the frontend or in slamengine, but John suggested I file this here.

**NOTE**: This issue only occurs in the bundled version of SlamData that is downloaded from our website. I cannot reproduce with my own build and the latest `slamengine` jar.

1. Launch SlamData
2. Add a new mount, click "Mount". This results in successful `PUT` call to the server.
3. I am redirected to `localhost:62562` (or another port: it is always a different port each time it happens). The new mount does not appear in the list (see #865).

Interestingly, this bug only *seems* to occur the first time I try to mount a database; the strange redirect does not happen again until I quit `SlamData.app` and restart it. (Similar behavior is observed in my other new ticket, #865).

**Comment by mossprescott** [comment] 2015-08-12 23:13
Almost certainly another symptom of #865. Please reopen if it's not fixed by the PR coming up shortly.

**Closed by mossprescott** 2015-08-12 23:13 UTC
Labels: bug, ready

**Comment by jdegoes** [comment] 2015-08-12 23:18
@mossprescott Can you give it a quick test? Plop in the SlamEngine JAR to the package that the installer builds and places in /Applications (of course, this assumes you can reproduce now).

**Comment by mossprescott** [comment] 2015-08-12 23:24
Sure, I'll try that as soon as the build script finishes here.

**Comment by mossprescott** [comment] 2015-08-12 23:51
I'm not seeing any redirect after overwriting the jar with my local build after the fix, and I did see some weird redirects before.

**Comment by jonsterling** [comment] 2015-08-17 21:40
@mossprescott @jdegoes For the record, I just observed this bug again by running the frontend's automated tests (against slamengine `v2.1.6`, in which version I think it is supposed to be fixed); it does not appear to be easily reproducible though.

**Comment by jdegoes** [comment] 2015-08-17 21:42
@jonsterling Timeouts never fix bugs, they just decrease their frequency. :smiling_imp: See #874.

**Comment by jonsterling** [comment] 2015-08-17 21:43
@jdegoes Heh, very well put. Feel free to close this ticket if it is superseded by #874.

**Comment by jdegoes** [comment] 2015-08-17 21:44
@jonsterling Yeah, #874 should be considered the definitive fix for this. Right now, it's expected to fail sometimes.

**Comment by jonsterling** [comment] 2015-08-17 21:44
@jdegoes Ok, thanks for the clarification!

**Comment by mossprescott** [comment] 2015-08-17 21:53
The behavior that I thought might be causing has been fixed, so I'm not sure what could be going on here and it may never have been related after all.

**Comment by jdegoes** [comment] 2015-08-17 21:57
@mossprescott I do believe that *not* restarting the server, but merely updating the config will solve this problem. Based on the symptoms, this problem was likely caused by two concurrent running servers, with the first one making changes to a config file that was overwritten by the second one, and the second one launching at a new port because of finding the first one still taken. So I'll leave this closed unless #874 doesn't fix it.
